config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :projects
  resources :invoices
  get "signup" => "users#new"
  resource :session, only: [:new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user

    validates :adress, :size, :date, presence: true
    validate :at_least_one_present
    validates :size, numericality: { only_integer: true }

    private

    def at_least_one_present
        unless drone.present? || video.present? || photo.present?
        errors.add(:base, "At least one of drone, video, or photo must be present")
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_secure_password

  validates :name, presence: true

  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        User.find(session[:user_id]) if session[:user_id]
    end

    helper_method :current_user

    def current_user?(user)
        current_user == user
    end

    helper_method :current_user?
    
    def is_admin?
        current_user && current_user.admin?
    end

    helper_method :is_admin?

    def require_signin
        unless current_user
            session[:intended_url] = request.url
            redirect_to new_session_url, alert: 'Please sign in first!'
        end
    end

    def require_admin
        unless is_admin?
            redirect_to events_url, alert: 'Unauthorized Access!'
        end
    end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
    def index
        @invoices = Invoice.all
    end
    def show
        @invoice = Invoice.find_by(params[:id])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    before_action :require_signin

    def index
        @projects = Project.all
    end

    def show
        @project = Project.find(params[:id])
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.new(project_params)
        @project.user_id = current_user.id
        if @project.save
            redirect_to project_path(@project), notice: 'Project successfully created!'
        else
            render :new, status: :unprocessable_entity
        end
    end
    
    private

    def project_params
        params.require(:project).permit(:adress, :date, :video, :drone, :photo, :size)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create 
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to (session[:intended_url] || user), notice: "Welcome back, #{user.name}!"
            session[:intended_url] = nil
        else
            flash.now[:alert] = "Invalid email/password combination!"
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to projects_url, status: :see_other
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_signin, except: [:new, :create]
    before_action :require_correct_user, only: [:edit, :update, :destroy]

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(params.require(:user).permit(:name, :email, :password, :password_confirmation))
        if @user.save
            redirect_to @user
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @user = User.find(params[:id]).destroy
        session[:user_id] = nil
        redirect_to events_url, status: :see_other
    end

    def require_correct_user
        @user = User.find(params[:id])
        redirect_to events_url unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/invoices/index.html.erb
<h1>Overview of all Invoices</h1>
<ul class="list-group">
    <% @invoices.each do |i| %>
        <li class="list-group-item"><%= link_to i.invoice_num, i %>, <%= i.price %>, <%= i.description %>, <%= i.customer_name %></li>
    <% end%>
</ul>

app/views/invoices/show.html.erb
<%= content_tag :h1, class: "text-light bg-info" do %>
  Invoice - <%= content_tag :span, "##{@invoice.invoice_num}" %>
<% end %>


<h2>Name: <%= @invoice.customer_name %></h2>
<h2>Description:</h2>
<p><%= @invoice.description %></p>
<h3>Price: <%= @invoice.price %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Realbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= render "shared/header" %>
      <%= render "shared/flash" %>
      <%= yield %>
      <%= render "shared/footer" %>
    </div>
  </body>

</html>

app/views/projects/_form.html.erb
<div class="container">
  <%= form_with(model: project, html: { class: "needs-validation", novalidate: true }) do |form| %>

    <%= render "shared/errors", object: project %>

    <div class="mb-3">
      <%= form.label :adress, class: "form-label" %>
      <%= form.text_field :adress, autofocus: true, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :date, class: "form-label" %>
      <%= form.datetime_select :date, class: "form-select" %>
    </div>

    <div class="mb-3">
      <%= form.label :size, class: "form-label" %>
      <%= form.number_field :size, class: "form-control" %>
    </div>

    <div class="mb-3 form-check">
      <%= form.check_box :photo, class: "form-check-input" %>
      <%= form.label :photo, class: "form-check-label" %>
    </div>

    <div class="mb-3 form-check">
      <%= form.check_box :video, class: "form-check-input" %>
      <%= form.label :video, class: "form-check-label" %>
    </div>

    <div class="mb-3 form-check">
      <%= form.check_box :drone, class: "form-check-input" %>
      <%= form.label :drone, class: "form-check-label" %>
    </div>

    <%= form.submit class: "btn btn-primary" %>

  <% end %>
</div>

app/views/projects/index.html.erb
<h1>All Projects Listed</h1>
<% if is_admin? %>
    <% @projects.each do |p| %>
        <div class="container">
            <h2>Created by <%= p.user.name %></h2>
            <ul class="list-group">
                <li class="list-group-item">Adress: <%= link_to p.adress, p %></li>
                <li class="list-group-item">Size of Property: <%= p.size %></li>
                <li class="list-group-item">Video: <%= p.video %></li>
                <li class="list-group-item">Drone: <%= p.drone %></li>
                <li class="list-group-item">Photo: <%= p.photo %></li>
            </ul>
            <br>
        </div>
    <% end%>
<% end %>
<% if current_user %>
    <%= link_to 'Create new Project', new_project_path(@project) %>
<% end %>

app/views/projects/new.html.erb
<h1>Create a new Project</h1>

<%= render "form", project: @project %>

app/views/projects/show.html.erb
<%= content_tag :h1, class: "text-light bg-info" do %>
  This is Project - <%= content_tag :span, @project.adress %>
<% end %>
<h2>Details:</h2>
<ul class="list-group">
    <li class="list-group-item">Date of occurance: <%= @project.date %></li>
    <li class="list-group-item">Video: <%= @project.video %></li>
    <li class="list-group-item">Drone: <%= @project.drone %></li>
    <li class="list-group-item">Photo: <%= @project.photo %></li>
</ul>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <section class="errors">
        <h2>
            Oops! Your data could not be saved.
        </h2>
        <h3>
            Please correct the following
            <%= pluralize(object.errors.size, "error") %>:
        </h3>
        <ul>
            <% object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </section>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= type %>%>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center text-lg-start bg-body-tertiary text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_header.html.erb
<header>
  <nav>
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <%= link_to 'Projects', projects_path, class: 'nav-link active' %>
      </li>
      <% if is_admin? %>
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: 'nav-link' %>
        </li>
      <% end %>
      <% if current_user %>
          <%= link_to 'Account', user_path(current_user), class: 'nav-link' %>
      <% end %>
      <% if is_admin? %>
        <li class="nav-item">
          <%= link_to 'Invoices', invoices_path, class: 'nav-link' %>
        </li>
      <% end %>
      <% if !current_user %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_session_path, class: 'nav-link', tabindex: '-1' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= current_user.name %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", session_path, data: { turbo_method: :delete }, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/users/edit.html.erb
<h1>Edit account details</h1>

<%= form_with(model: @user) do |f| %>

<%= render "shared/errors", object: @user %>

    <%= f.label :name %>
    <%= f.text_field :name , autofocus: true %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>

    <% if @user.new_record? %>
        <%= f.submit "Create Account" %>
    <% else %>
        <%= f.submit "Update Account" %>
    <% end %>

<% end %>

app/views/users/index.html.erb
<h1>List of all Users</h1>
<% @users.each do |u| %>
    <ul>
        <li><%= u.id %></li>
        <li><%= u.name %></li>
        <li><%= u.email %></li>
    </ul>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: @user) do |f| %>

<%= render "shared/errors", object: @user %>

    <%= f.label :name %>
    <%= f.text_field :name , autofocus: true %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>

    <% if @user.new_record? %>
        <%= f.submit "Create Account" %>
    <% else %>
        <%= f.submit "Update Account" %>
    <% end %>

<% end %>

app/views/users/show.html.erb
<h1>My account</h1>
<h2>Welcome <%= @user.name %> to your user account, here you will soon be able to make changes</h2>
<h3><%= @user.email %></h3>
<% if current_user?(@user) %>
    <%= link_to "Edit user", edit_user_path(@user) %>
<% end %>